"""migrazione2

Revision ID: db773d6736f5
Revises: ffd22cb2cbdd
Create Date: 2023-10-12 18:22:32.012032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db773d6736f5'
down_revision = 'ffd22cb2cbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruoli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('id_ruolo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ruolo'], ['ruoli.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utenti_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utenti_username'))

    op.drop_table('utenti')
    op.drop_table('ruoli')
    # ### end Alembic commands ###
