"""initial migration

Revision ID: ffd22cb2cbdd
Revises: 
Create Date: 2023-10-12 18:21:05.579960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd22cb2cbdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_index('ix_utenti_username')

    op.drop_table('utenti')
    op.drop_table('ruoli')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruoli',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('utenti',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id_ruolo', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_ruolo'], ['ruoli.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.create_index('ix_utenti_username', ['username'], unique=False)

    # ### end Alembic commands ###
